[tool.black]
line-length = 79

[tool.isort]
profile = "black"
known_django = "django"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
combine_as_imports=true
lines_between_types=true
line_length = 79
